package models.user;

public enum Permission {
    CREATE_RESOURCE, READ_RESOURCE, UPDATE_RESOURCE, DELETE_RESOURCE,
    CREATE_MODEL, READ_MODEL, UPDATE_MODEL,
    CREATE_GUIDELINE, READ_GUIDELINE, UPDATE_GUIDELINE, DELETE_GUIDELINE,
    CREATE_REPORT, READ_REPORT;
}
